apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordscontainer1
  labels:
    app: ordscontainer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordscontainer1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ordscontainer1
    spec:
      containers:
      - image: docker.io/oracle/restdataservices:21.4.2
        env:
        - name: ORACLE_HOST
          value: "140.87.125.194"
        - name: ORACLE_PORT
          value: "1521"
        - name: ORACLE_SERVICE
          value: "TCAPQO"
        - name: ORACLE_PWD
          value: "n_nGeu7wP9"
        - name: ORDS_PWD
          value: "Welcome1!"
        name: ordscontainer1
        volumeMounts: 
        - name: ords-vol
          mountPath: /opt/oracle/ords/config/ords
        ports:
        - containerPort: 8888
          name: ordscontainer1
        envFrom:
         - secretRef:
            name: ordspassword1
      volumes: 
      - name: ords-vol
        hostPath: 
         path: "/home/opc/ords_vol1"
      nodeSelector:
        app_name: ords_node

---
apiVersion: v1
kind: Service
metadata:
 name: ordscontainer1
spec:
 type: LoadBalancer
 selector:
   app: ordscontainer1
 ports:
   - name: client
     protocol: TCP
     port: 8888
     nodePort: 31009
